# Generated by Django 3.2.6 on 2022-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20220424_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_link',
            field=models.URLField(default='www.google.com', max_length=128),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_link',
            field=models.URLField(default='www.google.com', max_length=128),
        ),
    ]
